{"uid":"edbfdf8da0546f3c","name":"test_restore_on_new_cluster","fullName":"tests.integration.test_backups#test_restore_on_new_cluster","historyId":"bed98d44c46e16121bf35ab3fcc6a6f9","time":{},"description":"Test that is possible to restore a backup to another PostgreSQL cluster.","descriptionHtml":"<p>Test that is possible to restore a backup to another PostgreSQL cluster.</p>\n","status":"unknown","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"tag","value":"group(2)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_backups"},{"name":"host","value":"fv-az1113-533"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_backups"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":4,"skipped":29,"passed":0,"unknown":26,"total":59},"items":[{"uid":"80427752b85a3a24","reportUrl":"../138//#testresult/80427752b85a3a24","status":"unknown","time":{}},{"uid":"f0549729014ef92b","reportUrl":"../137//#testresult/f0549729014ef92b","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1723089484030,"stop":1723089484030,"duration":0}},{"uid":"6f18ffd4d78a4e1c","reportUrl":"../136//#testresult/6f18ffd4d78a4e1c","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1722999184306,"stop":1722999184306,"duration":0}},{"uid":"32937ca2da72992c","reportUrl":"../135//#testresult/32937ca2da72992c","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1722909538341,"stop":1722909538341,"duration":0}},{"uid":"18cf45a355fff1bb","reportUrl":"../134//#testresult/18cf45a355fff1bb","status":"unknown","time":{}},{"uid":"c069fbc694a1e105","reportUrl":"../133//#testresult/c069fbc694a1e105","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1722737425806,"stop":1722737425806,"duration":0}},{"uid":"cc9a6a17bc5f3620","reportUrl":"../132//#testresult/cc9a6a17bc5f3620","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1722657441491,"stop":1722657441491,"duration":0}},{"uid":"d27475f4860ddf0c","reportUrl":"../131//#testresult/d27475f4860ddf0c","status":"unknown","time":{}},{"uid":"6c74325b5854dbb9","reportUrl":"../130//#testresult/6c74325b5854dbb9","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1722479277839,"stop":1722479277839,"duration":0}},{"uid":"4956b84902439ce","reportUrl":"../129//#testresult/4956b84902439ce","status":"unknown","time":{}},{"uid":"433b5ed7b918ded0","reportUrl":"../128//#testresult/433b5ed7b918ded0","status":"unknown","time":{}},{"uid":"8927796d348fdb74","reportUrl":"../127//#testresult/8927796d348fdb74","status":"unknown","time":{}},{"uid":"faeec0d6965620a2","reportUrl":"../126//#testresult/faeec0d6965620a2","status":"unknown","time":{}},{"uid":"8828aecc54ffbbf2","reportUrl":"../125//#testresult/8828aecc54ffbbf2","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1722044118372,"stop":1722044118372,"duration":0}},{"uid":"1d26a1b13f78000f","reportUrl":"../124//#testresult/1d26a1b13f78000f","status":"broken","statusDetails":"kubernetes.client.exceptions.ApiException: (0)\nReason: Connection to remote host was lost.","time":{"start":1721957465512,"stop":1721957465512,"duration":0}},{"uid":"14b57de4e6be74bf","reportUrl":"../123//#testresult/14b57de4e6be74bf","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1721872166121,"stop":1721872166121,"duration":0}},{"uid":"421a8c70c09a9573","reportUrl":"../122//#testresult/421a8c70c09a9573","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=16443): Max retries exceeded with url: /api/v1/namespaces/controller-microk8s-localhost/services/controller-service (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90e71bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1721786430520,"stop":1721786430520,"duration":0}},{"uid":"2dddc69adcf052db","reportUrl":"../121//#testresult/2dddc69adcf052db","status":"unknown","time":{}},{"uid":"6ac4de849f8b7243","reportUrl":"../120//#testresult/6ac4de849f8b7243","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1721614403065,"stop":1721614403065,"duration":0}},{"uid":"67b6143b32fc5ffb","reportUrl":"../119//#testresult/67b6143b32fc5ffb","status":"unknown","time":{}}]},"tags":["asyncio","group(2)"]},"source":"edbfdf8da0546f3c.json","parameterValues":[]}